services:
  web:
    build: 
      context: .
      dockerfile: ./resources/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - ES_HOST=${ES_HOST}
      - ES_PORT=${ES_PORT}
      - ES_INDEX=${ES_INDEX}
